# Generated by Django 5.2.9 on 2025-12-20 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRentedEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rented_event_items', to='inventory.equipment')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rented_equipment_items', to='events.event')),
            ],
            options={
                'unique_together': {('event', 'equipment')},
            },
        ),
    ]
