# Generated by Django 5.2.9 on 2025-12-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventrentedequipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('confirmed', 'Подтверждено'), ('in_rent', 'В работе'), ('closed', 'Закрыто')], default='draft', max_length=20, verbose_name='Статус'),
        ),
    ]
