# Generated by Django 5.2.9 on 2026-01-14 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_equipment_tbd_alter_event_end_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': [('edit_event_card', 'Can edit event card (dates/status/etc)'), ('edit_event_equipment', 'Can edit event equipment (own/rented)')]},
        ),
    ]
