# Generated by Django 5.2.9 on 2026-01-19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='senior_engineer',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='events_as_senior',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Старший инженер',
            ),
        ),
        migrations.AddField(
            model_name='event',
            name='engineers',
            field=models.ManyToManyField(
                blank=True,
                related_name='events_as_engineer',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Инженеры',
            ),
        ),
    ]
