# Generated by Django 5.2.9 on 2026-01-29 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_soft_delete'),
        ('events', '0006_event_notes'),
    ]

    operations = [
    ]
