# Generated by Django 5.2.9 on 2026-01-14 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('manage_staff', 'Can manage staff (users/roles)')], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
