# Generated by Django 5.2.9 on 2026-02-18 10:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffinvite',
            name='is_used',
        ),
        migrations.AlterField(
            model_name='staffinvite',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_invites_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staffinvite',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='staffinvite',
            name='used_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_invites_used', to=settings.AUTH_USER_MODEL),
        ),
    ]
