# Generated by Django 5.2.9 on 2026-02-18 10:12

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_staffinvite_is_used_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='patronymic',
        ),
        migrations.AddField(
            model_name='user',
            name='patronymic',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='staffinvite',
            name='token',
            field=models.CharField(db_index=True, default=accounts.models.generate_invite_token, max_length=128, unique=True),
        ),
    ]
