# Generated by Django 5.2.9 on 2026-01-14 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'permissions': [('manage_inventory', 'Can manage inventory')]},
        ),
    ]
