# Generated by Django 5.2.9 on 2026-02-03 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stock_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockequipmenttype',
            name='dimensions_mm',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Габариты (мм)'),
        ),
        migrations.AddField(
            model_name='stockequipmenttype',
            name='power_w',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Потребляемая мощность (Вт)'),
        ),
        migrations.AlterField(
            model_name='stockequipmenttype',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.stockcategory'),
        ),
        migrations.AlterField(
            model_name='stockequipmenttype',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.stocksubcategory'),
        ),
    ]
