# Generated by Django 5.2.9 on 2026-02-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_stockequipmenttype_dimensions_mm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockequipmentitem',
            name='status',
            field=models.CharField(choices=[('storage', 'На складе'), ('event', 'На мероприятии'), ('repair', 'В ремонте')], default='storage', max_length=16),
        ),
    ]
